# Generated by Django 4.1.4 on 2022-12-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['-id']},
        ),
    ]
