# Generated by Django 4.0.6 on 2022-10-17 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_productinventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productname',
            new_name='product_name',
        ),
    ]
