# Generated by Django 4.1.4 on 2022-12-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductInventory',
        ),
    ]
