# Generated by Django 4.1.4 on 2022-12-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_delete_productinventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
